import { DataGrid } from "@material-ui/data-grid";
import styles from "../../../styles/MessageList.module.css"
import {useDispatch} from "react-redux";
import Link from "next/link"
import Topbar from "../../../components/Topbar";
import Sidebar from "../../../components/Sidebar";
import axios from "axios";
import {getMailSuccess} from "../../../redux/mailRedux";
import {getSession} from "next-auth/react";
import {DeleteOutline, MailOutlined} from "@material-ui/icons";
import AdminModal from "../../../components/AdminModal";
import React, {useState} from "react";
import Head from "next/head";

const MessageList = ({messages}) => {
    const [showModal, setShowModal] = useState(false)
    const [messageId, setMessageId] = useState("")
    const dispatch = useDispatch()
    dispatch(getMailSuccess(messages))
    const handleDelete = (id) => {
        setMessageId(id)
        setShowModal(true);
    }
    const columns = [
        { field: "_id", headerName: "ID", width: 80 },
        {
            field: "email",
            headerName: "Email",
            width: 150,
            renderCell: (params) => {
                return (
                    <div className={styles.mailListItem}>
                        {params.row.email}
                    </div>
                );
            },
        },
        { field: "firstName", headerName: "Voornaam", width: 120 },
        { field: "lastName", headerName: "Achternaam", width: 120 },
        { field: "phone", headerName: "Phone", width: 120 },
        { field: "message", headerName: "Message", width: 220 },


        {
            field: "action",
            headerName: "Action",
            width: 200,
            renderCell: (params) => {
                return (
                    <>
                        <Link passHref={"/admin/messages/" + params.row._id}>
                           <MailOutlined className={styles.mailListEdit}/>
                        </Link>
                   <DeleteOutline className={styles.mailListDelete} onClick={() => handleDelete(params.row._id)}/>
                    </>
                );
            },
        },
    ];

    return (
        <>
            <AdminModal showModal={showModal} setShowModal={setShowModal} title="messages" path="mail" id={messageId}/>
            <Topbar/>
            <div className={styles.container}>
                <Head>
                    <title>De Mobiele Slager</title>
                    <meta name="Chaam, NL Slager" content="Generated by me" />
                    <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@300;400;500;700&family=Rock+Salt&family=Sansita+Swashed:wght@500;600;700;800;900&display=swap" rel="stylesheet"/>
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <Sidebar/>
                <div className={styles.mail}>
                    <DataGrid
                        rows={messages}
                        disableSelectionOnClick
                        columns={columns}
                        getRowId={(row)=> row._id}
                        pageSize={10}
                        checkboxSelection
                    />
                </div>
            </div>
        </>
    );
};
export const getServerSideProps = async (context) =>{
    const session = await getSession({req: context.req})
    const message = await axios.get("http://localhost:3000/api/mail");
    if (!session) {
        return {
            redirect: {
                destination: '/admin/',
                permanent: false,
            },
        };
    }

    return{
        props:{
            session,
            messages: message.data
        }
    };
};

export default MessageList;


